service:
  name: hn-offline-services

package:
  individually: true

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10

functions:
  hello:
    handler: dist/hello.hello
    events:
      - http:
          method: get
          path: hello
  hn-api:
    handler: dist/hn-api.hn
    events:
      - http:
          method: get
          path: hn
