service:
  name: hn-offline-services

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
  hn-api:
    handler: src/hn-api.hn
    events:
      - http:
          method: get
          path: hn
